schema = 3

[mod]
  [mod."cloud.google.com/go"]
    version = "v0.26.0"
    hash = "sha256-VZjIft7Xp7HLMgv4SNqZAOtkdCVVYeJmflKd3f2VLEw="
  [mod."github.com/BurntSushi/toml"]
    version = "v1.1.0"
    hash = "sha256-1Mib3Aj/YhrlwA3o3x9orRRkVlYa5JRDQfNdtaUyeu0="
  [mod."github.com/OneOfOne/xxhash"]
    version = "v1.2.2"
    hash = "sha256-JvJnJFr9NFh5u+b7BgNEIwZR6scXW8l8RkT1DXmGTtY="
  [mod."github.com/alecthomas/kong"]
    version = "v0.5.0"
    hash = "sha256-6OtTXBnZSVvbdgkAfah2EuX20Fg/2v3JRSnKq1QoJbA="
  [mod."github.com/alecthomas/repr"]
    version = "v0.0.0-20210801044451-80ca428c5142"
    hash = "sha256-XUx+sN0wtc1j4t83sa5Z2MOBHxYQUUfsFfgfBeZqCUQ="
  [mod."github.com/armon/consul-api"]
    version = "v0.0.0-20180202201655-eb2c6b5be1b6"
    hash = "sha256-aVqUesaJyU/nrgwlfG2p16VxcF6Hyk4s8diMp0Nuzsg="
  [mod."github.com/cespare/xxhash"]
    version = "v1.1.0"
    hash = "sha256-nVDTtXH9PC3yJ0THaQZEN243UP9xgLi/clt5xRqj3+M="
  [mod."github.com/cespare/xxhash/v2"]
    version = "v2.1.1"
    hash = "sha256-cF+sDnnTZ1xRwjsy08SVSV/JoZalwY+dg0Zkghy6BNw="
  [mod."github.com/client9/misspell"]
    version = "v0.3.4"
    hash = "sha256-MIKnt4va/nPl+5cCgOvCyRGIORTnguieQhlj8ery4BU="
  [mod."github.com/coreos/etcd"]
    version = "v3.3.10+incompatible"
    hash = "sha256-fCyJRKX9dgcb2JwqiQL/OshS3Ilmm7bY3OCISxZ6l68="
  [mod."github.com/coreos/go-etcd"]
    version = "v2.0.0+incompatible"
    hash = "sha256-Uo5heUPCLTGZ8ns1Zi48kuNnPtvJ/7kLXpMGpT4kY/U="
  [mod."github.com/coreos/go-semver"]
    version = "v0.2.0"
    hash = "sha256-YFZP0mXFl1P1S0udGNP0AlZsfe0sMAy7g6BIbFeJ8L0="
  [mod."github.com/cpuguy83/go-md2man"]
    version = "v1.0.10"
    hash = "sha256-XP8oKAx5LgQ0fO1rjO9tWnbXB431VOzXVaRDPUP900g="
  [mod."github.com/cpuguy83/go-md2man/v2"]
    version = "v2.0.1"
    hash = "sha256-R+8iYit0mZjCxiGlp2C3Y5tGhySSNFU1v6wqsWKGBPM="
  [mod."github.com/davecgh/go-spew"]
    version = "v1.1.1"
    hash = "sha256-nhzSUrE1fCkN0+RL04N4h8jWmRFPPPWbCuDc7Ss0akI="
  [mod."github.com/dgraph-io/badger/v3"]
    version = "v3.2103.2"
    hash = "sha256-F6pvsaSKwXOl9RfnUQFqAl6xpCVu9+rthQgOxhKVk1g="
  [mod."github.com/dgraph-io/ristretto"]
    version = "v0.1.0"
    hash = "sha256-01jneg1+1x8tTfUTBZ+6mHkQaqXVnPYxLJyJhJQcvt4="
  [mod."github.com/dgryski/go-farm"]
    version = "v0.0.0-20190423205320-6a90982ecee2"
    hash = "sha256-PQ7kbI/liOpUeja/PpnkejJwG5HTENK2XGEDfZ8kdPQ="
  [mod."github.com/dustin/go-humanize"]
    version = "v1.0.0"
    hash = "sha256-gy4G1PnHD9iw2MitHX6y1y93qr3C9IncmXL7ttUMDs8="
  [mod."github.com/fsnotify/fsnotify"]
    version = "v1.4.7"
    hash = "sha256-j/Ts92oXa3k1MFU7Yd8/AqafRTsFn7V2pDKCyDJLah8="
  [mod."github.com/gogo/protobuf"]
    version = "v1.3.2"
    hash = "sha256-pogILFrrk+cAtb0ulqn9+gRZJ7sGnnLLdtqITvxvG6c="
  [mod."github.com/golang/glog"]
    version = "v0.0.0-20160126235308-23def4e6c14b"
    hash = "sha256-YDyL9TRikSXHSrYtITVA/ovYIYrdnZGym14XnslAYkk="
  [mod."github.com/golang/groupcache"]
    version = "v0.0.0-20190702054246-869f871628b6"
    hash = "sha256-fOnPnheIVato+xi3xc40UKw0vFLyd7IwKH2vJAKalmQ="
  [mod."github.com/golang/mock"]
    version = "v1.1.1"
    hash = "sha256-MFLrbygqwXNwXcaoRFgMQPC+g0gK4FyV6qopobXtOz0="
  [mod."github.com/golang/protobuf"]
    version = "v1.3.1"
    hash = "sha256-eLr0yrIO2wTtL+LvFKM3styaQSPnZQYSpaDjajBQT7Q="
  [mod."github.com/golang/snappy"]
    version = "v0.0.3"
    hash = "sha256-77y8JFRE3FcYd8CTypXnJlTJuog1pJg5WjhboFjTiLU="
  [mod."github.com/google/flatbuffers"]
    version = "v1.12.1"
    hash = "sha256-v9/ewAmNdQ4SNBlBwgHkxn3IVJAf31D7zVlxwEK/LRs="
  [mod."github.com/google/go-cmp"]
    version = "v0.5.5"
    hash = "sha256-pyfTIu1fx6cGYHhm+yi8YP2TgERnnqKRjqSV7WGb1Yk="
  [mod."github.com/hashicorp/hcl"]
    version = "v1.0.0"
    hash = "sha256-xsRCmYyBfglMxeWUvTZqkaRLSW+V2FvNodEDjTGg1WA="
  [mod."github.com/inconshreveable/mousetrap"]
    version = "v1.0.0"
    hash = "sha256-ogTuLrV40FwS4ueo4hh6hi1wPywOI+LyIqfNjsibwNY="
  [mod."github.com/kisielk/errcheck"]
    version = "v1.5.0"
    hash = "sha256-ZmocFXtg+Thdup+RqDYC/Td3+m1nS0FydZecfsWXIzI="
  [mod."github.com/kisielk/gotool"]
    version = "v1.0.0"
    hash = "sha256-lsdQkue8gFz754PGqczUnvGiCQq87SruQtdrDdQVTpE="
  [mod."github.com/klauspost/compress"]
    version = "v1.12.3"
    hash = "sha256-T+3MGtqRLdLu7WrGSaHPeJ5QLhwHmOM8K8eLxJK8n/o="
  [mod."github.com/kr/pretty"]
    version = "v0.1.0"
    hash = "sha256-Fx+TaNrxW0VfzonT2jnd5MU09RRz7GJZkqAtJR6/pKI="
  [mod."github.com/kr/pty"]
    version = "v1.1.1"
    hash = "sha256-AVeS+ivwNzIrgWQaLtsmO2f2MYGpxIVqdac/EzaYI1Q="
  [mod."github.com/kr/text"]
    version = "v0.1.0"
    hash = "sha256-QT65kTrNypS5GPWGvgnCpGLPlVbQAL4IYvuqAKhepb4="
  [mod."github.com/magiconair/properties"]
    version = "v1.8.0"
    hash = "sha256-tkt1yGEPbRjQvhsCkiD7jyLyhX2eo4AWx0ihzYUZIKg="
  [mod."github.com/mitchellh/go-homedir"]
    version = "v1.1.0"
    hash = "sha256-oduBKXHAQG8X6aqLEpqZHs5DOKe84u6WkBwi4W6cv3k="
  [mod."github.com/mitchellh/mapstructure"]
    version = "v1.1.2"
    hash = "sha256-OU9HZYHtl0qaqMFd84w7snkkRuRY6UMSsfCnL5HYdw0="
  [mod."github.com/nix-community/go-nix"]
    version = "v0.0.0-20220612195009-5f5614f7ca47"
    hash = "sha256-eBPzib8STUZnDpLFpWZz+F00thbp1P/98oiEE/XWE+M="
  [mod."github.com/pelletier/go-toml"]
    version = "v1.2.0"
    hash = "sha256-Yt9MGTbIaU/1FhE7SO5UCQbTLxe+2vsypTdf38i3kFY="
  [mod."github.com/pkg/errors"]
    version = "v0.9.1"
    hash = "sha256-mNfQtcrQmu3sNg/7IwiieKWOgFQOVVe2yXgKBpe/wZw="
  [mod."github.com/pmezard/go-difflib"]
    version = "v1.0.0"
    hash = "sha256-/FtmHnaGjdvEIKAJtrUfEhV7EVo5A/eYrtdnUkuxLDA="
  [mod."github.com/russross/blackfriday"]
    version = "v1.5.2"
    hash = "sha256-7MjJB7KZoNFTBo5Qzc3LL9QKrzWf9keqt5lh7tl360s="
  [mod."github.com/russross/blackfriday/v2"]
    version = "v2.1.0"
    hash = "sha256-R+84l1si8az5yDqd5CYcFrTyNZ1eSYlpXKq6nFt4OTQ="
  [mod."github.com/sirupsen/logrus"]
    version = "v1.8.1"
    hash = "sha256-vUIDlLXYBD74+JqdoSx+W3J6r5cOk63heo0ElsHizoM="
  [mod."github.com/spaolacci/murmur3"]
    version = "v1.1.0"
    hash = "sha256-RWD4PPrlAsZZ8Xy356MBxpj+/NZI7w2XOU14Ob7/Y9M="
  [mod."github.com/spf13/afero"]
    version = "v1.1.2"
    hash = "sha256-00yWOvw9GosWm6QkogM8MxpnVFRm/7BcdBLG4pQjO1Y="
  [mod."github.com/spf13/cast"]
    version = "v1.3.0"
    hash = "sha256-hbVF7F0YsgSybYEJa7W+Rz0As6OpgmpZOxB5JLFzAXc="
  [mod."github.com/spf13/cobra"]
    version = "v1.4.0"
    hash = "sha256-I6j9sD61Ztcc2W/WGeWo3ggYtnGTxNxZ2EFPdtO0UEY="
  [mod."github.com/spf13/jwalterweatherman"]
    version = "v1.0.0"
    hash = "sha256-KLftz+gaA5wSkvLqvQ7CuboB79kKEoTJvgTtrXatbiQ="
  [mod."github.com/spf13/pflag"]
    version = "v1.0.5"
    hash = "sha256-w9LLYzxxP74WHT4ouBspH/iQZXjuAh2WQCHsuvyEjAw="
  [mod."github.com/spf13/viper"]
    version = "v1.3.2"
    hash = "sha256-8I/LyWr7cOKg+0NokEbewJ8WNz8hp0KLUW0WgNyGSaA="
  [mod."github.com/stretchr/objx"]
    version = "v0.1.0"
    hash = "sha256-az0Vd4MG3JXfaYbj0Q6AOmNkrXgmXDeQm8+BBiDXmdA="
  [mod."github.com/stretchr/testify"]
    version = "v1.7.0"
    hash = "sha256-t1I9uCrn9vSUu/z5IZuNyGShmbOcJ6UGc2f75ZBrHzE="
  [mod."github.com/ugorji/go/codec"]
    version = "v0.0.0-20181204163529-d75b2dcb6bc8"
    hash = "sha256-GNABQN4JwB9w9GDUBUYG84soa9olIHiDWE/JdN4R4fc="
  [mod."github.com/xordataexchange/crypt"]
    version = "v0.0.3-0.20170626215501-b2862e3d0a77"
    hash = "sha256-HuXuIK/V5iNuF7j68acNQ3SW7rrn1efaI/Rfq0xBAxM="
  [mod."github.com/yuin/goldmark"]
    version = "v1.2.1"
    hash = "sha256-vrL87IsRgYTTHvCH2fodVu+ECk9UCu4kuCy3Ypy2Oos="
  [mod."go.opencensus.io"]
    version = "v0.22.5"
    hash = "sha256-1EhPgCDtRoeU1gYXud7cEUxZNaC6z1k8rpYbS8OeTBU="
  [mod."golang.org/x/crypto"]
    version = "v0.0.0-20200622213623-75b288015ac9"
    hash = "sha256-QvFbJEm3gXs2NtaaREbkbAtdHpU4fqX+0C0EvTezdKM="
  [mod."golang.org/x/exp"]
    version = "v0.0.0-20190121172915-509febef88a4"
    hash = "sha256-3aexxwjrNamNF7sKeDO0VhPMHbs+PPE4W1RisxYSHSo="
  [mod."golang.org/x/lint"]
    version = "v0.0.0-20190313153728-d0100b6bd8b3"
    hash = "sha256-x3rhw8oYIPlmZw4b80oNU5Tu8j/deZV2NCZK0lOuCiw="
  [mod."golang.org/x/mod"]
    version = "v0.5.1"
    hash = "sha256-+r/pAtwGHJiGISV/je8ZPXCFukTTGbZ8y0p3zb8wGcs="
  [mod."golang.org/x/net"]
    version = "v0.0.0-20201021035429-f5854403a974"
    hash = "sha256-QzW8gkznloAcMLjxEF3xj8KllpK8VTnflkOuEeLvKDw="
  [mod."golang.org/x/oauth2"]
    version = "v0.0.0-20180821212333-d2e6202438be"
    hash = "sha256-x0Lvhts17qZLPpt43EuNzUXcKJ6krpGWLYiA0Fw5dnE="
  [mod."golang.org/x/sync"]
    version = "v0.0.0-20201020160332-67f06af15bc9"
    hash = "sha256-hfvviA1/duBMtleic86KvYNlUz3/V7XKVAggZtUldyQ="
  [mod."golang.org/x/sys"]
    version = "v0.0.0-20220610221304-9f5ed59c137d"
    hash = "sha256-/qCatdMn+M1Lbu10CK0kQtLCmYDBXtIQ1kdy2F/2hlc="
  [mod."golang.org/x/text"]
    version = "v0.3.3"
    hash = "sha256-kiauoT7vd7Mh2AW7TnceQyoCDsARxWkDZu1OSD9dCZw="
  [mod."golang.org/x/tools"]
    version = "v0.0.0-20210106214847-113979e3529a"
    hash = "sha256-VdoV0LIBWehslesNW1ETJ1WmO4KsGojC2HDdNAjGzsI="
  [mod."golang.org/x/xerrors"]
    version = "v0.0.0-20220609144429-65e65417b02f"
    hash = "sha256-tl8pv3oddbz2+KoIp7PFDKsxjQF8ocjPF8XPsY3sw38="
  [mod."google.golang.org/appengine"]
    version = "v1.4.0"
    hash = "sha256-F6BEJekXXq0IT8Is1oBB1/ea+2a1RwNl+NyTI2mOXpg="
  [mod."google.golang.org/genproto"]
    version = "v0.0.0-20190425155659-357c62f0e4bb"
    hash = "sha256-gZ08J0jio7VotNGOPmwcBB1OI/W51raJ6uhh9JUhfBI="
  [mod."google.golang.org/grpc"]
    version = "v1.20.1"
    hash = "sha256-K23JYIB6cVqULRrJh8YPktmUTy9OETGobp5uN63haPE="
  [mod."gopkg.in/check.v1"]
    version = "v1.0.0-20190902080502-41f04d3bba15"
    hash = "sha256-Xl5gjoqU26M+Yxm6Xok5VHVpYT5hItwsN7d2Wj9L020="
  [mod."gopkg.in/yaml.v2"]
    version = "v2.4.0"
    hash = "sha256-uVEGglIedjOIGZzHW4YwN1VoRSTK8o0eGZqzd+TNdd0="
  [mod."gopkg.in/yaml.v3"]
    version = "v3.0.0-20210107192922-496545a6307b"
    hash = "sha256-j8yDji+vqsitpRZirpb4w/Em8nstgf28wpwkcrOlxBk="
  [mod."honnef.co/go/tools"]
    version = "v0.0.0-20190102054323-c2f93a96b099"
    hash = "sha256-cmKu1iXynQZvRglt4mZ0JiX3uPr9O6B9azsTQ4MC/qI="
